### ISSUE TITLE
How to upload Google Cloud KEY in github??

### ISSUE THREAD

**Issue by LimSeJin9577** [2021-KPANG/AI-Online-Meeting-Solution#10]
구글 클라우드 키를 github페이지에 올려서 심사위원분들도 자유롭게 사용할 수 있게 만들고 싶습니다..
키를 github에 올리면 gmail로 올리지말라고 경고장이 오는데, key를 public으로 바꾸는 방법을 아시는분이 있을까요?

**Comment by SoYoungCho** [comment]
경고장이 몇 번 누적되면 발급이 중단될까요?

**Comment by LimSeJin9577** [comment]
> 경고장이 몇 번 누적되면 발급이 중단될까요?

Dear Developer,
--
We've detected that your Google Cloud Project My First Project (id: summer-avenue-303505) appears to be  committing repeated Google Cloud Platform Terms of Service violations.To avoid suspension of all impacted resources in 72 hours, please take the following steps to protect your project:Your project may have  been compromised, therefore we recommend that you secure all your instances.Submit an appeal: Sign in to My First Project (id: summer-avenue-303505) as the project owner, click Request an appeal below, and fill in the following details:Steps taken to fix the problemIf the behavior is intentional, explain the business reasons why this violation may existLearn more about policy violations and appealsIf you need further help, please reach out to the Google Cloud Platform Community Support Forum. If you have a support package, please file a ticket through the Support Center.We appreciate your help in correcting this issue.

라고 문자가 옵니다.
72시간내에 키사용이 일시 중지된다고 하는데 단 몇시간 만에도 되는것 같아요
어차피 KPMG에 공개하려면 KEY 정책문제는 해결해야할 것 같습니다.

+ API_KEY를 만들어서 배포하려고 하는데 잘 안되네요..! 그것도 컴퓨터마다 설정해주는게 좋다고 하구요.

**Comment by SoYoungCho** [comment]
직접 다운 받도록 설명 작성했습다 :>
